name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        live_cd: ["i686-gnupg"]
    steps:
      - uses: actions/checkout@v2

      # Available versions of Nix:
      # https://github.com/nixbuild/nix-quick-install-action/releases.
      - uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_version: 2.21.0
          nix_conf: experimental-features = nix-command flakes

      - run: nix build ./${{ matrix.live_cd }}/.#nixosConfigurations.default.config.system.build.isoImage

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.live_cd }}
          path: |
            result/iso/*
